= Scheme index site
:icons: font
:toc: left

Static site frontend for https://github.com/schemeorg-community/scheme-index content.

Deployed at https://index.scheme.org.

== Building static site GUI

[IMPORTANT]
.Make sure git submodule containing the data is checked out
====
[code,sh]
----
git submodule update --init
----
====

. (option 1) Build natively
.. Install:
... Chicken scheme compiler;
... `json`, `matchable`, `srfi 1` chicken eggs;
... nodejs and npm.
.. Execute `bash build.sh` in `build` directory
. (option 2) Build with docker
.. Install docker
.. Execute in `build` directory:
+
[code,sh]
----
docker build -f ./Dockerfile .. -t scheme-index:latest
docker create --name dummy scheme-index:latest
docker cp dummy:/schemeindex.zip ./schemeindex.zip
docker rm -f dummy
----
. You'll find `schemeindex.zip` after successful build, which you can deploy from any web server.

If you plan serving not from root, edit `index.html` file and change `<base href=".">` to point to appropriate prefix.

The site uses html5 routing. To enable entering the site from any route, you have to configure web server to serve index.html for paths that don't match static resources. E.g., in nginx:

[code,nginx]
----
        location / {
            try_files $uri $uri/ /index.html =404;
        }
----

== Running in development

[IMPORTANT]
.Make sure git submodule containing the data is checked out
====
[code,sh]
----
git submodule update --init
----
====

=== Natively

. Install:
.. Chicken scheme compiler;
.. `json`, `matchable`, `srfi 1` chicken eggs;
.. nodejs and npm.
. Build json data files from primary sexpr data (only need to do it once initially; or when you want to rebuild from latest upstream data):
+
[code,sh]
----
cd scheme-index-util
csc buildtypes.scm
csc buildfilters.scm
cd ..
./scheme-index-util/buildtypes data/types/index.scm scheme-index-app/src/assets/types.json
./scheme-index-util/buildfilters data/filters/index.scm scheme-index-app/src/assets/filters.json
----
. From `scheme-index-app`:
.. Execute `npm i` (Only need to do it once initially, and after package.json changes);
.. Run `npm run start`
. The site will be available at http://localhost:4200.

=== Docker compose

Run `docker compose up` from `build` directory, the site will be available at http://localhost:8080.
